Improve error messages

diff --git a/bin/git-pr-checkout b/bin/git-pr-checkout
--- a/bin/git-pr-checkout
+++ b/bin/git-pr-checkout
@@ -2,9 +2,18 @@
 
 set -euo pipefail
 
-readonly remote_url="$(git ls-remote --get-url)"
+remote_url="$(git ls-remote --get-url)"
+readonly remote_url=$remote_url
 
-pr_number=$1
+set +u
+if [[ -z "$1" ]]
+then
+	echo "You need to provied a pr number." >&2
+	exit 1
+else
+	pr_number=$1
+fi
+set -u
 
 case "$remote_url" in
 	*github.*)
@@ -12,8 +21,11 @@ case "$remote_url" in
 		;;
 	*gitlab.*)
 		echo 'Not yet implemented for gitlab' >&2
-		exit 1 ;;
+		exit 2 ;;
 	*bitbucket.*)
 		echo 'Not yet implemented for bitbucket' >&2
+		exit 2 ;;
+	*)
+		echo "Could not macht remote url: $remote_url" >&2
 		exit 1 ;;
 esac
diff --git a/bin/git-pr-open b/bin/git-pr-open
--- a/bin/git-pr-open
+++ b/bin/git-pr-open
@@ -2,9 +2,10 @@
 
 set -euo pipefail
 
-readonly remote_url="$(git ls-remote --get-url)"
+remote_url="$(git ls-remote --get-url)"
+readonly remote_url=$remote_url
 
-push=$1
+push="${1:-}"
 function push() {
     [[ "$push" = '--push' ]]
 }
@@ -24,6 +25,7 @@ case "$remote_url" in
         # Use GitHub's cli to create the PR from the branch.
         gh pr create --fill
         ;;
+
     *gitlab.*)
         if ! push
         then
@@ -31,7 +33,9 @@ case "$remote_url" in
             read -rp "Continue? (y/n): " yn
             [[ "$yn" =~ [Yy].* ]] || exit 1
         fi
-        git -c push.default=current push -o merge_request.create ;;
+        git -c push.default=current push -o merge_request.create
+        ;;
+
     *bitbucket.*)
         if push
         then
@@ -40,5 +44,8 @@ case "$remote_url" in
 
         git-pr_open_bitbucket "$remote_url"
         ;;
-    *) exit 1;;
+
+    *)
+        echo "Could not match remote url: $remote_url"
+        exit 1 ;;
 esac
